/**
 * Author:  shoeltker
 * Created: 20.01.2021
 */

/****** Object:  Table [dbo].[LAUFLOG]    Script Date: 20.01.2021 14:12:26 ******/
CREATE TABLE [dbo].[LAUFLOG](
  [ID_NUM] INT IDENTITY(1,1),
	[SCHNITTSTELLE] [varchar](10) NOT NULL,
	[VERSION] [varchar](255) NOT NULL,
	[LAUF] [varchar](10) NOT NULL,
	[LEVEL] [nvarchar](10) NULL,
	[EVENTDATE] [datetime] NULL,
	[THREAD] [nvarchar](4000) NULL,
	[LOGGER] [nvarchar](1000) NULL,
	[TEXT] [nvarchar](max) NULL,
 CONSTRAINT [PK_LAUFLOG] PRIMARY KEY CLUSTERED 
(
	[SCHNITTSTELLE] ASC,
	[VERSION] ASC,
	[LAUF] ASC,
	[ID_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO